services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
      - JELLYFIN_PublishedServerUrl=$JELLYFIN_URL
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    volumes:
      - ./configs/jellyfin:/config
      - $DATA_DIRECTORY/media:/data/media
    networks:
      - default_network
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
    volumes:
      - ./configs/radarr:/config
      - $DATA_DIRECTORY:/data
      - ./data2:/data2
    networks:
      - default_network
    ports:
      - 7878:7878
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
    volumes:
      - ./configs/sonarr:/config
      - $DATA_DIRECTORY:/data
      - ./data2:/data2
    networks:
      - default_network
    ports:
      - 8989:8989
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
    volumes:
      - ./configs/prowlarr:/config
    networks:
      - default_network
    ports:
      - 9696:9696
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=$TIMEZONE
    networks:
      - default_network
    ports:
      - 8191:8191
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
    volumes:
      - ./configs/sabnzbd:/config
      - $DATA_DIRECTORY/usenet:/data/usenet
      - ./data2/usenet:/data2/usenet
    networks:
      - default_network
    ports:
      - $SABNZBD_PORT:$SABNZBD_PORT
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
      - WEBUI_PORT=8082
      - TORRENTING_PORT=$QBITTORRENT_INCOMING_CONNECTIONS_PORT
    volumes:
      - ./configs/qbittorrent:/config
      - $DATA_DIRECTORY/torrents:/data/torrents
      - ./data2/torrents:/data2/torrents
    networks:
      - default_network
    ports:
      - 8082:8082
      - $QBITTORRENT_INCOMING_CONNECTIONS_PORT:$QBITTORRENT_INCOMING_CONNECTIONS_PORT
      - $QBITTORRENT_INCOMING_CONNECTIONS_PORT:$QBITTORRENT_INCOMING_CONNECTIONS_PORT/udp
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - TZ=$TIMEZONE
    volumes:
      - ./configs/bazarr:/config
      - $DATA_DIRECTORY/media:/data/media
    networks:
      - default_network
    ports:
      - 6767:6767
    restart: always

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: $USER_ID:$GROUP_ID
    volumes:
      - ./configs/recyclarr:/config
    environment:
      - TZ=$TIMEZONE
    networks:
      - default_network
    restart: always

networks:
  default_network:
    name: default_network
    external: true
