services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    volumes:
      - ./configs/linuxserver/jellyfin:/config
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/radarr:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/sonarr:/config
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${QBITTORRENT_INCOMING_CONNECTIONS_PORT}
    volumes:
      - ./configs/linuxserver/qbittorrent:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
    ports:
      - 8080:8080
      - ${QBITTORRENT_INCOMING_CONNECTIONS_PORT}:${QBITTORRENT_INCOMING_CONNECTIONS_PORT}
      - ${QBITTORRENT_INCOMING_CONNECTIONS_PORT}:${QBITTORRENT_INCOMING_CONNECTIONS_PORT}/udp
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/bazarr:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
    ports:
      - 6767:6767
    restart: unless-stopped
