services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    volumes:
      - ./configs/linuxserver/jellyfin:/config
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${OTHERS_DIRECTORY}/data/others:/data/others
    networks:
      - default_network
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/radarr:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
    networks:
      - default_network
    ports:
      - 7878:7878
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/sonarr:/config
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
    networks:
      - default_network
    ports:
      - 8989:8989
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/prowlarr:/config
    networks:
      - default_network
    ports:
      - 9696:9696
    restart: always

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    shm_size: 2gb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs/byparr/screenshots:/app/screenshots
    networks:
      - default_network
    ports:
      - 8191:8191
    restart: always

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/sabnzbd:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
      - ${OTHERS_DIRECTORY}/data/others:/data/others
    networks:
      - default_network
    ports:
      - ${SABNZBD_PORT}:${SABNZBD_PORT}
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8082
      - TORRENTING_PORT=${QBITTORRENT_INCOMING_CONNECTIONS_PORT}
    volumes:
      - ./configs/linuxserver/qbittorrent:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
      - ${OTHERS_DIRECTORY}/data/others:/data/others
    networks:
      - default_network
    ports:
      - 8082:8082
      - ${QBITTORRENT_INCOMING_CONNECTIONS_PORT}:${QBITTORRENT_INCOMING_CONNECTIONS_PORT}
      - ${QBITTORRENT_INCOMING_CONNECTIONS_PORT}:${QBITTORRENT_INCOMING_CONNECTIONS_PORT}/udp
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ./configs/linuxserver/bazarr:/config
      - ${MOVIES_DIRECTORY}/data/movies:/data/movies
      - ${TV_SHOWS_DIRECTORY}/data/tvshows:/data/tvshows
    networks:
      - default_network
    ports:
      - 6767:6767
    restart: always

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./configs/recyclarr:/config
    environment:
      - TZ=${TIMEZONE}
    networks:
      - default_network
    restart: always

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:dev
    container_name: decluttarr
    restart: always
    environment:
      - TZ=${TIMEZONE}
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./configs/decluttarr/config:/app/config
      - ./configs/decluttarr/logs:/app/logs
    networks:
      - default_network

networks:
  default_network:
    name: default_network
    external: true
